spring:
  application:
    name: SNPC-ERP
server:
  servlet:
    context-path: /api
  port: 8888


# Configuration de l'API de base
base-api:
  url: http://localhost:9999
  timeout:
    connect: 5000
    read: 30000