name: Deploy snpc back
on: [push]
env:
  IMAGE: snpc-erp
  VERSION: 0.0.1
jobs:
  create-folder:
    name: Create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir /opt/applications/fodecc/${{ env.IMAGE }}
            ls -al /opt/applications/fodecc
  generate-image:
    name: Generate image
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: Cloner le repertoire
        uses: actions/checkout@main
      - name: Setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate and push image
        run: |
          ./mvnw clean package spring-boot:build-image \
          -Ddocker.publishRegistry.username=${{ secrets.DOCKER_USERNAME }} \
          -Ddocker.publishRegistry.password=${{ secrets.DOCKER_PASSWORD }} \
          -Dspring-boot.build-image.publish=true \
          -Dmaven.test.skip=true
  run-container:
    name: Run container
    runs-on: ubuntu-latest
    needs: ['create-folder', 'generate-image']
    steps:
      - name: Cloner le repertoire
        uses: actions/checkout@main
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "compose.yml"
          target: /opt/applications/fodecc/${{ env.IMAGE }}
      - name: execute commands to run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo BASE_SNPC_HOST="${{ secrets.BASE_SNPC_HOST }}" > /opt/applications/fodecc/${{ env.IMAGE }}/.env
            docker compose -f /opt/applications/fodecc/${{ env.IMAGE }}/compose.yml up -d
            rm /opt/applications/fodecc/${{ env.IMAGE }}/.env